resources:
  jobs:
    example_workflow_1:
      name: example_workflow_1
      tasks:
        - task_key: notebook1
          notebook_task:
            notebook_path: workflow1/notebook1
            source: GIT
          job_cluster_key: Job_cluster
        - task_key: notebook2
          notebook_task:
            notebook_path: workflow1/notebook2
            source: GIT
          job_cluster_key: Job_cluster
        - task_key: notebook3
          depends_on:
            - task_key: notebook1
            - task_key: notebook2
          notebook_task:
            notebook_path: workflow1/notebook3
            source: GIT
          job_cluster_key: Job_cluster
      job_clusters:
        - job_cluster_key: Job_cluster
          new_cluster:
            cluster_name: ""
            spark_version: 13.3.x-scala2.12
            aws_attributes:
              first_on_demand: 1
              availability: SPOT_WITH_FALLBACK
              zone_id: us-east-2a
              spot_bid_price_percent: 100
              ebs_volume_count: 0
            node_type_id: i3.xlarge
            spark_env_vars:
              PYSPARK_PYTHON: /databricks/python3/bin/python3
            enable_elastic_disk: false
            data_security_mode: SINGLE_USER
            runtime_engine: PHOTON
            num_workers: 8
      git_source:
        git_url: https://github.com/randall-gonzalez-dbx/ci_cd_lab.git
        git_provider: gitHub
        git_branch: dev
      tags:
        prod_target: prod_A
        test_target: test_A
